version: '3'
services:
  backend:
    image:
      - diyasylum/formserver
    ports:
     - "8080:8080"
  frontend:
    build: ../../diy_asylum_frontend
    command:
      - nodemon
      - server.js
    ports:
     - "3000:3000"
